version: '3.8'

services:
  # Serviço da aplicação Spring Boot
  app:
    build: .
    ports:
      - "8080:8080" # Expor a porta 8080 do container para o host
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/database
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db # Garantir que o banco de dados suba antes da aplicação
    networks:
      - app-network

  # Serviço do banco de dados MySQL
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: database
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/mysql # Persistir dados no volume

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
    driver: local
