# Identificador único para o projeto no SonarQube
sonar.projectKey=Esfera

# Nome do projeto (opcional)
sonar.projectName=Esfera
# Versão do projeto (opcional)
sonar.projectVersion=1.0

# URL do servidor SonarQube
sonar.host.url=http://localhost:9000

# Autenticação com usuário e senha
sonar.login=admin
sonar.password=Admin123456.

# Diretório que contém o código-fonte (use '.' para a raiz do projeto)
sonar.sources=.

# Linguagem principal do projeto (opcional, SonarQube geralmente detecta automaticamente)
sonar.language=java

# Excluir arquivos ou diretórios específicos (opcional)
sonar.exclusions=**/tests/**,**/*.xml

# Configurações adicionais para análise em Java (remova se não for Java)
sonar.java.binaries=target/classes

# Excluir arquivos de teste da cobertura de código (opcional)
sonar.test.exclusions=**/*Test.java
